spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/stackoverflow
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD:admin1!}

management.endpoint.health.show-details=always